<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>PJATK_APBD_Cw8_s32101</RootNamespace>
        <UserSecretsId>f6c23b3f-6bae-446c-96d3-85376592484e</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.15"/>
    </ItemGroup>

</Project>
